---
apiVersion: v1
kind: Service
metadata:
  name: persistencecore-firehose-merger
  labels:
    app.kubernetes.io/name: persistencecore-firehose-merger
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: persistencecore-firehose-merger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistencecore-firehose-merger
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: persistencecore
      app.kubernetes.io/name: persistencecore-firehose-merger
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: persistencecore
        app.kubernetes.io/type: persistencecore-firehose-merger
        app.kubernetes.io/name: persistencecore-firehose-merger
        app.kubernetes.io/version: '0.1'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: firehose-merger-node
          image: betterpersist/firecosmos:0.6.0
          imagePullPolicy: Always
          env:
            - name: FIRST_STREAMBLE_BLOCK
              valueFrom:
                configMapKeyRef:
                  key: first_streamable_block
                  name: firehose-node-config
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: firehose-node-aws-credentials
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: firehose-node-aws-credentials
            - name: ONE_BLOCK_STORE_URL
              valueFrom:
                configMapKeyRef:
                  key: one_block_store_url
                  name: firehose-node-config
            - name: MERGED_BLOCKS_STORE_URL
              valueFrom:
                configMapKeyRef:
                  key: merged_blocks_store_url
                  name: firehose-node-config
          command:
            - bash
            - "-c"
            - |
              export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              exec firecosmos start merger \
                --common-live-blocks-addr persistencecore-firehose-reader.$NAMESPACE.svc.cluster.local:9010 \
                --common-first-streamable-block $FIRST_STREAMBLE_BLOCK
                --common-one-block-store-url $ONE_BLOCKS_STORE_URL \
                --common-merged-blocks-store-url $MERGED_BLOCKS_STORE_URL
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "1"
              memory: "1G"
      volumes:
        - name: config-graph
          configMap:
            name: config-graph
        - name: scripts-graph
          configMap:
            name: scripts-graph