---
apiVersion: v1
kind: Service
metadata:
  name: persistencecore-firehose-reader
  labels:
    app.kubernetes.io/name: persistencecore-firehose-reader
spec:
  clusterIP: None
  ports:
    - name: reader-grpc
      port: 10010
      protocol: TCP
      targetPort: 10010
    - name: prometheus-node
      port: 26660
      protocol: TCP
      targetPort: 26660
    - name: prometheus-firehose
      port: 9102
      protocol: TCP
      targetPort: 9102
  selector:
    app.kubernetes.io/name: persistencecore-firehose-reader
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: persistencecore-firehose-reader
spec:
  serviceName: persistencecore-firehose-reader
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: persistencecore
      app.kubernetes.io/name: persistencecore-firehose-reader
  template:
    metadata:
      annotations:
        quality: release
        role: api-gateway
        sla: high
        tier: gateway
      labels:
        app.kubernetes.io/instance: persistencecore
        app.kubernetes.io/type: persistencecore-firehose-reader
        app.kubernetes.io/name: persistencecore-firehose-reader
        app.kubernetes.io/version: '0.1'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: firehose-node
          image: ghcr.io/persistenceone/firecore-firepersistence:0.1
          imagePullPolicy: Always
          env:
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: chain.id
                  name: persistencecore
            - name: HOME_DIR
              value: /persistencecore
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws_access_key_id
                  name: firehose-node-aws-credentials
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws_secret_access_key
                  name: firehose-node-aws-credentials
            - name: ONE_BLOCK_STORE_URL
              valueFrom:
                configMapKeyRef:
                  key: one_block_store_url
                  name: firehose-node-config
            - name: MERGED_BLOCKS_STORE_URL
              valueFrom:
                configMapKeyRef:
                  key: merged_blocks_store_url
                  name: firehose-node-config
            - name: FIRST_STREAMABLE_BLOCK
              valueFrom:
                configMapKeyRef:
                  key: first_streamable_block
                  name: firehose-node-config
          command:
            - bash
            - "-c"
            - |
              exec firecore start reader-node \
                --config-file= \
                --log-format=stackdriver \
                --log-to-file=false \
                --data-dir=/fh-data \
                --common-auto-max-procs \
                --common-auto-mem-limit-percent=90 \
                --common-one-block-store-url "$ONE_BLOCK_STORE_URL" \
                --common-merged-blocks-store-url "$MERGED_BLOCKS_STORE_URL" \
                --common-first-streamable-block $FIRST_STREAMABLE_BLOCK \
                --reader-node-data-dir=/fh-data/oneblock \
                --reader-node-working-dir=/fh-data/work \
                --reader-node-readiness-max-latency=600s \
                --reader-node-debug-firehose-logs=false \
                --reader-node-blocks-chan-capacity=1000 \
                --reader-node-path=firepersistence \
                --reader-node-arguments="fetch rpc $FIRST_STREAMABLE_BLOCK --state-dir /fh-data --block-fetch-batch-size=1 --endpoints https://rpc.core.persistence.one:443 --max-block-fetch-duration 10s" \
                --advertise-chain-name "$CHAIN_ID"
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              cpu: "0.5"
              memory: "1G"
          # No volume mounts needed when not restoring snapshots
      # No additional volumes required
  volumeClaimTemplates:
  - metadata:
      name: node-pv-storage
    spec:
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
