apiVersion: v1
kind: ConfigMap
metadata:
  name: persistencecore
data:
  chain.id: test-core-2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: firehose-node-config
data:
  sync_node.resolution_method: STATIC
  sync_node.host: ''
  sync_node.exposer_port: ''
  sync_node.port_p2p: '26656'
  sync_node.genesis_json_fetch_url: https://raw.githubusercontent.com/persistenceOne/networks/master/test-core-2/genesis.json
  snapshot_restore_url: https://files.audit.one/persistence/snapshot/test-core-2/test-core-2-Jun-01.tar.lz4
  seeds: ''
  persistent_peers: 'cee6b94965f301e8b5ad905a65fa39c03cd193ce@51.68.152.17:26656,7f971fc5fc2ffedbaf32f3b4021645571461a712@198.244.177.67:26656'
  # For buffer time to sync the node
  first_streamable_block: '60000'
  force_init: 'false'
  one_block_store_url: 's3://sgp1.digitaloceanspaces.com/dexter-zone/testnet-2/one-blocks?region=us-east-1'
  merged_blocks_store_url: 's3://sgp1.digitaloceanspaces.com/dexter-zone/testnet-2/merged-blocks?region=us-east-1'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-node-config
data:
  firehose_node.host: 'persistencecore-firehose.testnet.svc.cluster.local'
  firehose_node.port: '9030'
  ipfs.host: 'ipfs-node.graph-test-core-1.svc.cluster.local'
  ipfs.port: '5001'